# Collector specific configuration
# This download URL is not used, as it is overridden in run.py, but the zip file gives a useful indication of the data structure
# download_url: "https://www.dropbox.com/s/9z2q521dq2vs1dx/HDX_Sample.zip?dl=0"

# Here is the list of resources, which includes the filename, and all the relevant metadata
resources:
  end_year_population_totals:
    file: HDX_EndYearPopulationTotals.csv
    residing:
      title: "End-year stock population figures for forcibly displaced and stateless persons residing in {countryname}"
      name: "unhcr-population-forcibly-displaced-residing-{countryiso}"
      description: |
        Data collated by UNHCR, containing end-year stock population figures for forcibly displaced and stateless persons residing in {countryname}.
        Data is available since 1951.
    originating:
      title: "End-year stock population figures for forcibly displaced persons originating from {countryname}"
      name: "unhcr-population-forcibly-displaced-originating-{countryiso}"
      description: |
        Data collated by UNHCR, containing end-year stock population figures for forcibly displaced persons originating from {countryname}.
        Data is available since 1951.
  asylum_applications:
    file: HDX_AsylumApplications.csv
    residing:
      title: "Asylum applications by asylum seekers residing in {countryname}"
      name: "unhcr-asylum-seekers-residing-{countryiso}"
      description: |
        Dataset collated by UNHCR, containing information about
        the number of applications for asylum residing in {countryname}. Data is available since 2000.
    originating: 
      title: "Asylum applications by asylum seekers originating from {countryname}"
      name: "unhcr-asylum-seekers-originating-{countryiso}"
      description: |
        Data collated by UNHCR, containing information about
        the number of applications for asylum originating from {countryname}.
        Data is available since 2000.
  asylum_decisions:
    file: HDX_AsylumDecisions.csv
    residing:
      title: "Asylum decisions taken on asylum claims of asylum seekers residing in {countryname}"
      name: "unhcr-asylum-decisions-residing-{countryiso}"
      description: |
        Data collated by UNHCR about asylum decisions taken on asylum claims of asylum seekers residing in {countryname}.
        Data is available since 2000.
    originating: 
      title: "Asylum decisions taken on asylum claims of asylum seekers originating from {countryname}"
      name: "unhcr-asylum-decisions-originating-{countryiso}"
      description: |
        Data collated by UNHCR about asylum decisions taken on asylum claims of asylum seekers originating from {countryname}.
        Data is available since 2000.
  demographics:
    file: HDX_Demographics.csv
    residing:
      title: "Demographics and locations of forcibly displaced and stateless people residing in {countryname}"
      name: "unhcr-demographics-residing-{countryiso}"
      description: |
        Data collated by UNHCR, containing information about forcibly displaced populations
        and stateless people residing in {countryname}. It includes data on their demographics as well as sub-national locations.
        The demographic data is only collected annually and data is available from 2001.
    originating: 
      title: "Demographics and locations of forcibly displaced people originating from {countryname}"
      name: "unhcr-demographics-originating-{countryiso}"
      description: |
        Data collated by UNHCR, containing information about forcibly displaced populations
        originating from {countryname}. It includes data on their demographics as well as sub-national locations.
        The demographic data is only collected annually and data is available from 2001.
  solutions:
    file: HDX_Solutions.csv
    residing:
      title: "Solutions for refugees and IDPs residing in {countryname}"
      name: "unhcr-solutions-residing-{countryiso}"
      description: |
        Data collated by UNHCR, containing information about the number of forcibly displaced
        residing in {countryname} availing different types of solutions for refugees and IDPs such as
        repatriation or resettlement. Data is available since 1983.
    originating: 
      title: "Solutions for refugees and IDPs originating from {countryname}"    
      name: "unhcr-solutions-originating-{countryiso}"
      description: |
        Dataset collated by UNHCR, containing information about the number of forcibly displaced
        originating from {countryname} availing different types of solutions for refugees and IDPs such as
        repatriation or resettlement. Data is available since 1983.

# And then here are the list of fields
fields:
  ASY:
    name: Asylum seekers
  ASY_incoming:
    name: Asylum seekers Incoming
  ASY_outgoing:
    name: Asylum seekers Outgoing
  AccommodationType:
    name: Accommodation Type
  ApplicationAveragePersonsPerCase:
    name: Application Average Persons Per Case
  ApplicationDataType:
    name: Application Data Type
    encoding:
      name: Application Data
      map:
        C: Cases
        P: Persons
  ApplicationType:
    name: Application Type Code
    encoding:
      name: Application Type
      map:
        N:  New
        R:  Repeat
        A:  Appeal
        NA: New and appeal
        NR: New and repeat
        FA: First and appeal
        RA: Repeat/reopened
        J:  Judiciary
        BL: Backlog
        SP: Subsidiary protection
        V: Various
  Applications:
    name: Number of Applications
  Applications_incoming:
    name: Number of Applications Incoming
  Applications_outgoing:
    name: Number of Applications Outgoing
  DecisionDataType:
    name: Decision Data Type
    encoding:
      name: Decision Data
      map:
        C: Cases
        P: Persons
  DecisionType:
    name: Decision Type Code
    encoding:
      expand: false
      name: Decision Type
      map:
         NA: New Applications
         FI: First instance decisions
         AR: Administrative Review decisions
         RA: Repeat/reopened
         IN: US Citizenship and Immigration Services
         EO: US Executive Office of Immigration Review
         JR: Judicial Review
         SP: Subsidiary protection
         FA: First instance and appeal
         TP: Temporary protection
         TA: Temporary asylum
         BL: Backlog
         TR: Temporary outside the asylum procedure
         CA: Cantonal regulations in Switzerland
  DecisionsAveragePersonsPerCase:
    name: Decisions Average Persons Per Case
  Female_0_4:
    name: Female 0-4
  Female_5_11:
    name: Female 5-11
  Female_12_17:
    name: Female 12-17
  Female_18_59:
    name: Female 18-59
  Female_60:
    name: Female 60 or more
  Female_Unknown:
    name: Female Unknown
  Female_total:
    name: Female Total
  IDP:
    name: Internally displaced persons
  IDP_incoming:
    name: Internally displaced persons Incoming
  IDP_outgoing:
    name: Internally displaced persons Outgoing
  ISO3CoO:
    name: Country of Origin Code
  ISO3CoA:
    name: Country of Asylum Code
  CoO_name:
    name: Country of Origin Name
  CoA_name:
    name: Country of Asylum Name
  Location:
    name: Location
  Male_0_4:
    name: Male 0-4
  Male_5_11:
    name: Male 5-11
  Male_12_17:
    name: Male 12-17
  Male_18_59:
    name: Male 18-59
  Male_60:
    name: Male 60 or more
  Male_Unknown:
    name: Male Unknown
  Male_total:
    name: Male Total
  NAT:
    name: Naturalisation
  NAT_incoming:
    name: Naturalisation Incoming
  NAT_outgoing:
    name: Naturalisation Outgoing
  OOC:
    name: Others of concern to UNHCR
  OOC_incoming:
    name: Others of concern to UNHCR Incoming
  OOC_outgoing:
    name: Others of concern to UNHCR Outgoing
  OtherwiseClosed:
    name: Otherwise Closed
  PopulationType:
    name: Population Type
  PT:
    name: Population Type
  ProcedureType:
    name: Procedure Type
    encoding:
      name: Procedure Name
      map:
        G: Government
        U: UNHCR
        J: Joint
  RDP:
    name: IDP returns
  REF:
    name: Refugees
  REF_incoming:
    name: Refugees Incoming
  REF_outgoing:
    name: Refugees Outgoing
  RET:
    name: Refugee returns
  RST:
    name: Resettlement arrivals
  Recognized:
    name: Recognized
  RecognizedOther:
    name: Complementary Protection
  Rejected:
    name: Rejected
  STA:
    name: Stateless Persons
  STA_incoming:
    name: Stateless Persons Incoming
  STA_outgoing:
    name: Stateless Persons Outgoing
  Total:
    name: Total
  TotalDecided:
    name: Total Decided
  UrbanRural:
    name: Urban or Rural
  OIP:
    name: Other people in need of international protection
  OIP_incoming:
    name: Other people in need of international protection Incoming
  OIP_outgoing:
    name: Other people in need of international protection Outgoing
  HST:
    name: Host community
  HST_incoming:
    name: Host community Incoming
  HST_outgoing:
    name: Host community Outgoing
  Year:
    name: Year

