# Collector specific configuration
download_url: "https://www.dropbox.com/s/9z2q521dq2vs1dx/HDX_Sample.zip?dl=0"
# On Linux
#source_directory: data
# On Windows
source_directory: '/Dropbox/UNHCR Statistics/Data/HDX/'

resources:
  asylum_applications:
    file: HDX_AsylumApplications.csv
    residing:
      title: 'Asylum applications by asylum-seekers residing in {countryname}'
      name: 'unhcr-asylum-seekers-residing-{countryiso}'
      description: |
        Dataset collated by UNHCR, containing information about
        the number of applications for asylum residing in {countryname}. Data is available since 2000.
    originating: 
      title: 'Asylum applications by asylum-seekers originating from {countryname}'
      name: 'unhcr-asylum-seekers-originating-{countryiso}'
      description: |
        Data collated by UNHCR, containing information about
        the number of applications for asylum originating from {countryname}. 
        Data is available since 2000.
  asylum_decisions:
    file: HDX_AsylumDecisions.csv
    residing:
      title: 'Asylum decisions taken on asylum claims of asylum-seekers residing in {countryname}'
      name: 'unhcr-asylum-decisions-residing-{countryiso}'
      description: |
        Data collated by UNHCR about asylum decisions taken on asylum claims of asylum-seekers residing in {countryname}.  
        Data is available since 2000.
    originating: 
      title: 'Asylum decisions taken on asylum claims of asylum-seekers originating from {countryname}'
      name: 'unhcr-asylum-decisions-originating-{countryiso}'
      description: |
        Data collated by UNHCR about asylum decisions taken on asylum claims of asylum-seekers originating from {countryname}.  
        Data is available since 2000.
  demographics:
    file: HDX_Demographics.csv
    residing:
      title: 'Demographics and locations of forcibly displaced and stateless persons residing in {countryname}'
      name: 'unhcr-demographics-residing-{countryiso}'
      description: |
        Data collated by UNHCR, containing information about forcibly displaced populations
        and stateless persons residing in {countryname}. It includes data on their demographics as well as sub-national locations.
        Data is available from 2001.
    originating: 
      title: 'Demographics and locations of forcibly displaced persons originating from {countryname}'    
      name: 'unhcr-demographics-originating-{countryiso}'
      description: |
        Data collated by UNHCR, containing information about forcibly displaced populations
        originating from {countryname}. It includes data on their demographics as well as sub-national locations.
        Data is available from 2001.
  end_year_population_totals:
    file: HDX_EndYearPopulationTotals.csv
    residing:
      title: 'End-year stock population figures for forcibly displaced and stateless persons residing in {countryname}'
      name: 'unhcr-population-forcibly-displaced-residing-{countryiso}'
      description: |
        Data collated by UNHCR, containing end-year stock population figures for forcibly displaced and stateless persons residing in {countryname}.
        Data is available since 1951.
    originating: 
      title: 'End-year stock population figures for forcibly displaced persons originating from {countryname}'    
      name: 'unhcr-population-forcibly-displaced-originating-{countryiso}'
      description: |
        Data collated by UNHCR, containing end-year stock population figures for forcibly displaced persons originating from {countryname}. 
        Data is available since 1951.
  solutions:
    file: HDX_Solutions.csv
    residing:
      title: 'Solutions for refugees and IDPs residing in {countryname}'
      name: 'unhcr-solutions-residing-{countryiso}'
      description: |
        Data collated by UNHCR, containing information about the number of forcibly displaced
        residing in {countryname} availing different types of solutions for refugees and IDPs such as
        repatriation or resettlement. Data is available since 1983.
    originating: 
      title: 'Solutions for refugees and IDPs originating from {countryname}'    
      name: 'unhcr-solutions-originating-{countryiso}'
      description: |
        Dataset collated by UNHCR, containing information about the number of forcibly displaced
        originating from {countryname} availing different types of solutions for refugees and IDPs such as
        repatriation or resettlement. Data is available since 1983.


fields:
  ASY:
    name: Asylum-seekers
    tags: '#indicator+num+value+asylum_seeker'
  AccommodationType:
    name: Accommodation Type
    tags: '#indicator+accommodation'
  ApplicationAveragePersonsPerCase:
    name: Application Average Persons Per Case
    tags: '#indicator+average+num+value+applications+percase'
  ApplicationDataType:
    name: Application Data Type
    tags: '#meta+application+unit+code'
    encoding:
      name: Application Data
      tags: '#meta+application+unit+name'
      map:
        C: Cases
        P: Persons
  ApplicationType:
    name: Application Type Code
    tags: '#meta+application+kind+code'
    encoding:
      name: Application Type
      tags: '#meta+application+kind+name'
      map:
        N:  New
        R:  Repeat
        A:  Appeal
        NA: New and appeal
        NR: New and repeat
        FA: First and appeal
        J:  Judiciary
        BL: Backlog 
        SP: Subsidiary protection
  Applications:
    name: Number of Applications
    tags: '#indicator+num+value+applications+total'
  DecisionDataType:
    name: Decision Data Type
    tags: '#meta+decision+unit+code'
    encoding:
      name: Decision Data
      tags: '#meta+decision+unit+name'
      map:
        C: Cases
        P: Persons
  DecisionType:
    name: Decision Type Code
    tags: '#meta+decision+code'
    encoding:
      expand: false
      name: Decision Type
      tags: '#meta+decision+name'
      map:
         NA: New Applications
         FI: First instance decisions
         AR: Administrative Review decisions
         RA: Repeat/reopened applications
         IN: US Citizenship and Immigration Services
         EO: US Executive Office of Immigration Review
         JR: Judicial Review
         SP: Subsidiary protection
         FA: First instance and appeal
         TP: Temporary protection
         TA: Temporary asylum
         BL: Backlog
         TR: Temporary outside the asylum procedure
         CA: Cantonal regulations in Switzerland
  DecisionsAveragePersonsPerCase:
    name: Decisions Average Persons Per Case
    tags: '#indicator+average+num+value+decisions+percase'
  Female_0_4:
    name: Female 0-4
    tags: '#population+f+infants+age0_4+num+value'
  Female_12_17:
    name: Female 12-17
    tags: '#population+f+adolescents+age12_17+num+value'
  Female_18_59:
    name: Female 18-59
    tags: '#population+f+adults+num+age18_59+value'
  Female_5_11:
    name: Female 5-11
    tags: '#population+f+children+age5_11+num+value'
  Female_60:
    name: Female 60 or more
    tags: '#population+f+elderly+age60plus+num+value'
  Female_Unknown:
    name: Female Unknown
    tags: '#population+f+ageunknown+num+value'
  Female_total:
    name: Female Total
    tags: '#population+f+total+num+value'
  IDP:
    name: Internally Displaced Persons
    tags: '#indicator+num+value+idp'
  ISO3CoA:
    name: Country of Asylum Code
    tags: '#country+code+iso+asylum'
  ISO3CoO:
    name: Country of Origin Code
    tags: '#country+code+iso+origin'
  Location:
    name: Location
    tags: '#loc'
  Male_0_4:
    name: Male 0-4
    tags: '#population+m+infants+age0_4+num+value'
  Male_12_17:
    name: Male 12-17
    tags: '#population+m+adolescents+age12_17+num+value'
  Male_18_59:
    name: Male 18-59
    tags: '#population+m+adults+age18_59+num+value'
  Male_5_11:
    name: Male 5-11
    tags: '#population+m+children+age5_11+num+value'
  Male_60:
    name: Male 60 or more
    tags: '#population+m+elderly+age60plus+num+value'
  Male_Unknown:
    name: Male Unknown
    tags: '#population+m+ageunknown+num+value'
  Male_total:
    name: Male Total
    tags: '#population+m+total+num+value'
  NAT:
    name: Naturalisation
    tags: '#indicator+num+value+naturalisation'
  OOC:
    name: Others of Concern to UNHCR
    tags: '#indicator+num+value+others_of_concern'
  OtherwiseClosed:
    name: Otherwise Closed
    tags: '#population+otherwise+closed+num+value'
  PopulationType:
    name: Population Type
    tags: '#meta+code+population+type'
  ProcedureType:
    name: Procedure Type
    tags: '#action+procedure+code'
    encoding:
      name: Procedure Name
      tags: '#action+procedure+name'
      map:
        G: Government
        U: UNHCR
        J: Joint
  RDP:
    name: IDP returns
    tags: '#indicator+num+value+returns+idp'
  REF:
    name: Refugees
    tags: '#indicator+num+value+refugee'
  RET:
    name: Refugee returns
    tags: '#indicator+num+value+returns+refugee'
  RST:
    name: Resettlement arrivals
    tags: '#indicator+num+value+resettlement+arrivals'
  Recognized:
    name: Recognized
    tags: '#population+recognized+num+value'
  RecognizedOther:
    name: Complementary Protection
    tags: '#population+recognized+other+num+value'
  Rejected:
    name: Rejected
    tags: '#population+rejected+num+value'
  STA:
    name: Stateless persons
    tags: '#indicator+num+value+stateless'
  Total:
    name: Total
    tags: '#population+i+total+num+value'
  TotalDecided:
    name: Total Decided
    tags: '#population+total+decided+num+value'
  UrbanRural:
    name: Urban or Rural
    tags: '#indicator+urban+rural'
  VDA:
    name: Venezuelans Displaced Abroad
    tags: '#indicator+num+value+venezuelans+displaced+abroad'
  Year:
    name: Year
    tags: '#date+year'


